# Generated by Django 4.1.3 on 2022-12-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First_name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last_name')),
                ('user_name', models.CharField(max_length=50, verbose_name='User_name')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
            ],
        ),
    ]
