# Generated by Django 4.1.3 on 2022-12-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_name',
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=50, null=True, verbose_name='Username'),
        ),
    ]
