# Generated by Django 4.1.3 on 2022-12-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_users_user_name_users_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datametric', models.CharField(max_length=50, verbose_name='datametric')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('images', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
